/**
 * Expo Config Plugin: Force kotlin-stdlib to a single version across all Gradle
 * configurations. This prevents Kotlin stdlib version conflicts that can cause
 * `IncompatibleClassChangeError` or duplicate class errors at build time.
 *
 * Equivalent to manually adding to android/build.gradle:
 *
 *   configurations.all {
 *     resolutionStrategy.force 'org.jetbrains.kotlin:kotlin-stdlib:1.9.10'
 *   }
 *
 * In the Expo managed workflow, `android/` is generated by EAS at prebuild time,
 * so we inject the directive programmatically via withProjectBuildGradle.
 */
const { withProjectBuildGradle } = require("expo/config-plugins");

const KOTLIN_FORCE_VERSION = "1.9.10";
const MARKER = "// signo:kotlin-stdlib-force";

const FORCE_BLOCK = `
${MARKER}
allprojects {
  configurations.all {
    resolutionStrategy {
      force 'org.jetbrains.kotlin:kotlin-stdlib:${KOTLIN_FORCE_VERSION}'
      force 'org.jetbrains.kotlin:kotlin-stdlib-jdk7:${KOTLIN_FORCE_VERSION}'
      force 'org.jetbrains.kotlin:kotlin-stdlib-jdk8:${KOTLIN_FORCE_VERSION}'
      force 'org.jetbrains.kotlin:kotlin-stdlib-common:${KOTLIN_FORCE_VERSION}'
    }
  }
}
`;

const withKotlinStdlibForce = (config) => {
  return withProjectBuildGradle(config, (mod) => {
    if (mod.modResults.language !== "groovy") {
      console.warn(
        "[withKotlinStdlibForce] android/build.gradle is not Groovy — skipped."
      );
      return mod;
    }

    // Idempotent: don't append twice if user re-runs prebuild
    if (mod.modResults.contents.includes(MARKER)) {
      return mod;
    }

    mod.modResults.contents = mod.modResults.contents.trimEnd() + "\n" + FORCE_BLOCK;
    return mod;
  });
};

module.exports = withKotlinStdlibForce;
